# This is a basic workflow to help you get started with Actions

name: obfuscate_accounts

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      #- name: Install dependencies
        #run: |
          #python -m pip install  --upgrade pip
          #pip install re
      - run: python clearPasswordsFromSnaplogicAccountFiles.py
      
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config ${{ github.actor }}

      - name: commit
        run: |
          # Stage the file, commit and push
          git add "Test IFS Account.sla"
          git commit -m "Removed passwords from Account()"
          git push origin main
